### ISSUE TITLE
Can't get it working with NPM

### ISSUE THREAD

**Issue by numbertree** [shootermv/angular2-material-chips#11]
I have executed following steps: 

> 1. ng new my-all 
> 2. npm i --save angular2-material-chips
> 3. Updated files as per instruction:
```

component.html: 
<material-chips [(ngModel)]="tags" ></material-chips>

component.ts 
export class AppComponent {
    tags:string[]  = ['AngularJS','Angluar2']
}

app.module.ts
import {MaterialChipsModule} from 'angular2-material-chips';
 
@NgModule({
    ...
    imports: [BrowserModule, MaterialChipsModule, FormsModule]
})

```
When I tried to test it, it was giving me error:

> Can't bind to 'ngModel' since it isn't a known property of 'material-chips'.

So I added NO_SCHEMA_ERROR to app.module.ts 
```
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
...
 schemas: [ NO_ERRORS_SCHEMA ]
```

Now the input is being displayed but there are 2 issues: 
1. Inital values are not displayed
2. When I try to add new one I am getting error in console: 

> ERROR TypeError: Cannot read property 'push' of undefined
>     at MaterialChipsComponent.webpackJsonp.../../../../angular2-material-chips/lib/material-
>

**Comment by shootermv** [comment]
Hi numbertree,  grate to see somebody is using my plugin.  Thanks for opening issue. Trying to check whats gone wrong. Thanks

**Comment by numbertree** [comment]
Dear @shootermv , 
Please do not bother any more. I didn't include FormsComponent therefore NgModel didn't work. However, there is another issue. It seems that I always have to use "values" property name within the example provided by you you are using "tags" but it doesn't work. Could you have a look at that?
